### ISSUE TITLE
publish().ref_count() and retry changed behaviour 

### ISSUE THREAD

**Issue by diorcety** [ReactiveX/RxCpp#405]
I developped last year a code which worked well on the current version at this time.
I tried to use the last rxcpp version and I have now issues.

I used a publish().ref_count() on a observable(zipped with an inverval in order to schedule each X seconds some request), and retry in order to continue on the next value from the observable.
I used to work. For example the following example loops on the 3 first values instead to continue on the next value.

Was I incorrectly used an operator incorrect behaviour or is there an issue?

```
    auto publish = ::rxcpp::observable<>::range<int>(0, 10).publish().ref_count();
    ::rxcpp::observable<char> obs = publish.flat_map([=](auto m) {
        printf("HANDLE %d\n", m);
        return ::rxcpp::observable<>::create<char>([=](::rxcpp::subscriber<char> subscriber) {
            if (m == 3) {
                subscriber.on_error(::std::make_exception_ptr(::std::runtime_error("Abcd")));
            } else {
                subscriber.on_next(m);
                subscriber.on_completed();
            }
        });
    }, [](auto m, auto b) {
        return b;
    }).retry();

    obs.subscribe([](const auto &a) {
        printf("ECHO %d\n", a);
    });
```

```
HANDLE 0
ECHO 0
HANDLE 1
ECHO 1
HANDLE 2
ECHO 2
HANDLE 3
HANDLE 0
ECHO 0
HANDLE 1
ECHO 1
HANDLE 2
ECHO 2
HANDLE 3
HANDLE 0
ECHO 0
HANDLE 1
ECHO 1
...
```

**Comment by kirkshoop** [comment]
This starts over from zero because of the `ref_count()` on `publish`. The `on_error` unsubscribes the only subscription and then the `retry` starts a new subscription.

These were some lifetime fixes in operators that were listed as breaking changes in past releases that might have exposed this. 

I think that your original code will work if you change `ref_count()` to `connect_forever()`. But the above code will not because the range will complete before the `retry()` can resubscribe.
